module.exports = {
  content: [
    './*.html',
    './*.js',
    './*.jsx',
    './functions/**/*.js'
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#123356',
        'primary-container': '#2c4a6e',
        'primary-fixed': '#d3e4ff',
        'primary-fixed-dim': '#abc9f3',
        'on-primary': '#ffffff',
        'on-primary-container': '#9cbae4',
        'on-primary-fixed': '#001c38',
        'on-primary-fixed-variant': '#2a486c',
        'inverse-primary': '#abc9f3',
        'surface-tint': '#436085',
        secondary: '#735b28',
        'secondary-container': '#fedb9c',
        'secondary-fixed': '#ffdea3',
        'secondary-fixed-dim': '#e3c285',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#785f2b',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#594312',
        tertiary: '#313332',
        'tertiary-container': '#484948',
        'tertiary-fixed': '#e3e2e0',
        'tertiary-fixed-dim': '#c7c6c5',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#b8b8b6',
        'on-tertiary-fixed': '#1a1c1b',
        'on-tertiary-fixed-variant': '#464746',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#faf9fc',
        surface: '#faf9fc',
        'surface-bright': '#faf9fc',
        'surface-dim': '#dad9dd',
        'surface-card': '#FFFFFF',
        'surface-variant': '#e3e2e5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f3f6',
        'surface-container': '#eeedf1',
        'surface-container-high': '#e9e8eb',
        'surface-container-highest': '#e3e2e5',
        'inverse-surface': '#2f3033',
        'inverse-on-surface': '#f1f0f4',
        'on-background': '#1a1c1e',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#43474e',
        outline: '#73777f',
        'outline-variant': '#c3c6cf',
        'sidebar-bg': '#F5F2EE',
        'border-warm': '#E8E4DE',
        'skeleton-shimmer': '#F0EDE8',
        'ink-text': '#1A1A2E',
        'glass-backdrop': 'rgba(26, 26, 46, 0.5)',
        'iso-p-blue': '#3B82F6',
        'iso-m-amber': '#F59E0B',
        'iso-k-red': '#EF4444',
        'iso-n-green': '#10B981',
        'iso-s-orange': '#F97316',
        'iso-h-slate': '#64748B'
      },
      spacing: {
        gutter: '24px',
        'card-padding': '20px',
        'container-margin': '32px',
        'sidebar-width': '260px',
        'stack-gap-sm': '8px',
        'stack-gap-md': '16px',
        'stack-gap-lg': '24px'
      },
      fontFamily: {
        'display-hero': ['Nunito', 'sans-serif'],
        'section-heading': ['Nunito', 'sans-serif'],
        'product-grade': ['Nunito', 'sans-serif'],
        'nav-item': ['Nunito', 'sans-serif'],
        'body-lg': ['DM Sans', 'sans-serif'],
        'body-md': ['DM Sans', 'sans-serif'],
        'label-caps': ['DM Sans', 'sans-serif'],
        'technical-data': ['DM Mono', 'monospace']
      },
      fontSize: {
        'label-caps': ['13px', { lineHeight: '1.0', letterSpacing: '0.06em', fontWeight: '600' }],
        'nav-item': ['15px', { lineHeight: '1.0', fontWeight: '500' }],
        'section-heading': ['28px', { lineHeight: '1.3', fontWeight: '700' }],
        'technical-data': ['14px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-md': ['17px', { lineHeight: '1.7', fontWeight: '400' }],
        'body-lg': ['19px', { lineHeight: '1.7', fontWeight: '400' }],
        'product-grade': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-hero': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '800' }]
      }
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ]
};
