insert into public.products (
  sku,
  brand,
  family,
  type_geometry,
  coating,
  material_compat,
  machine_type,
  application,
  alternatives_to,
  price_hint_eur,
  source_url,
  last_updated,
  notes
)
values
  ('CNMG 120408-PM','Sandvik','Turning','CNMG 120408-PM / C / Roughing','GC4325',array['P'],array['Wet','Dry'],array['Roughing','Continuous P-group turning'],array[]::text[],18,'Legacy directory migration','2024-08-01','Source: Manufacturer data | grade=GC4325 | iso=P | op=Roughing | confidence=96 | id=T01 | coolant=Wet/Dry | stability=High'),
  ('DNMG 150608','Mitsubishi','Turning','DNMG 150608 / D / Roughing','MC6025',array['P'],array['Wet'],array['Roughing','Medium P-group roughing'],array[]::text[],11,'Legacy directory migration','2024-06-01','Source: Manufacturer data | grade=MC6025 | iso=P | op=Roughing | confidence=90 | id=T02 | coolant=Wet | stability=High'),
  ('CNMG 120412-NF4','Walter','Turning','CNMG 120412-NF4 / C / Finishing','WPP20S',array['P'],array['Wet','Dry'],array['Finishing','Continuous steel finishing'],array['CNMG 120408-PM'],18,'Legacy directory migration','2024-09-01','Source: Manufacturer data | grade=WPP20S | iso=P | op=Finishing | confidence=94 | id=T03 | coolant=Wet/Dry | stability=High'),
  ('SNMG 120408-MP','Kennametal','Turning','SNMG 120408-MP / S / Mixed','KCP25C',array['P'],array['Wet'],array['Mixed','Versatile steel turning'],array[]::text[],18,'Legacy directory migration','2024-05-01','Source: Manufacturer data | grade=KCP25C | iso=P | op=Mixed | confidence=89 | id=T04 | coolant=Wet | stability=Medium'),
  ('WNMG 080408-NM','Iscar','Turning','WNMG 080408-NM / W / Mixed','IC8150',array['P'],array['Wet'],array['Mixed','Heavy P-group turning'],array[]::text[],11,'Legacy directory migration','2024-07-01','Source: Manufacturer + reviewed | grade=IC8150 | iso=P | op=Mixed | confidence=87 | id=T05 | coolant=Wet | stability=High'),
  ('VCMT 160404','Iscar','Turning','VCMT 160404 / V / Finishing','IC907',array['M'],array['Wet'],array['Finishing','Stainless finishing'],array[]::text[],11,'Legacy directory migration','2024-08-01','Source: Manufacturer data | grade=IC907 | iso=M | op=Finishing | confidence=91 | id=T06 | coolant=Wet | stability=High'),
  ('TPMR 220408','Sandvik','Reaming','TPMR 220408 / T / Prep','GC1025',array['M'],array['Wet'],array['Prep','Stainless threading prep'],array[]::text[],18,'Legacy directory migration','2024-04-01','Source: Manufacturer + reviewed | grade=GC1025 | iso=M | op=Prep | confidence=85 | id=T07 | coolant=Wet | stability=High'),
  ('CCMT 09T308-SM','Mitsubishi','Turning','CCMT 09T308-SM / C / Finishing','VP15TF',array['M'],array['Wet'],array['Finishing','Stainless light finishing'],array[]::text[],11,'Legacy directory migration','2024-09-01','Source: Manufacturer data | grade=VP15TF | iso=M | op=Finishing | confidence=92 | id=T08 | coolant=Wet | stability=High'),
  ('DCMT 11T304-HM','Korloy','Turning','DCMT 11T304-HM / D / Mixed','PC9030',array['M'],array['Wet'],array['Mixed','Mixed M-group turning'],array[]::text[],6,'Legacy directory migration','2024-02-01','Source: Generated estimate | grade=PC9030 | iso=M | op=Mixed | confidence=78 | id=T09 | coolant=Wet | stability=Medium'),
  ('CNMG 120408-KR','Kennametal','Turning','CNMG 120408-KR / C / Roughing','KCK15B',array['K'],array['Dry'],array['Roughing','Cast iron heavy turning'],array[]::text[],18,'Legacy directory migration','2024-07-01','Source: Manufacturer data | grade=KCK15B | iso=K | op=Roughing | confidence=89 | id=T10 | coolant=Dry | stability=High'),
  ('SNMG 120408-KM','Sandvik','Turning','SNMG 120408-KM / S / Mixed','GC3210',array['K'],array['Dry'],array['Mixed','Grey cast iron versatile'],array[]::text[],18,'Legacy directory migration','2024-09-01','Source: Manufacturer data | grade=GC3210 | iso=K | op=Mixed | confidence=93 | id=T11 | coolant=Dry | stability=Medium'),
  ('WCMX 06T308-53','Kennametal','Drilling','WCMX 06T308-53 / W / Roughing','KC7325',array['K'],array['Wet'],array['Roughing','Cast iron heavy drilling'],array[]::text[],18,'Legacy directory migration','2024-06-01','Source: Manufacturer + reviewed | grade=KC7325 | iso=K | op=Roughing | confidence=88 | id=T12 | coolant=Wet | stability=High'),
  ('880-D2200L25-02','Sandvik','Drilling','880-D2200L25-02 / D / Indexable','GC4044',array['K'],array['Wet'],array['Indexable','Indexable drilling cast iron'],array[]::text[],18,'Legacy directory migration','2024-08-01','Source: Manufacturer data | grade=GC4044 | iso=K | op=Indexable | confidence=90 | id=T13 | coolant=Wet | stability=High'),
  ('A-TAP 8.5x125','OSG','Drilling','A-TAP 8.5x125 / Solid','V-HSS',array['K'],array['Wet'],array['Solid','HSS solid drill general purpose'],array[]::text[],6,'Legacy directory migration','2024-03-01','Source: Manufacturer + reviewed | grade=V-HSS | iso=K | op=Solid | confidence=82 | id=T14 | coolant=Wet | stability=Medium'),
  ('SCGT 120408-AL','Mitsubishi','Milling','SCGT 120408-AL / S / HSM','AP25N',array['N'],array['MQL'],array['HSM','Aluminium high-speed mill'],array[]::text[],6,'Legacy directory migration','2024-09-01','Source: Manufacturer data | grade=AP25N | iso=N | op=HSM | confidence=93 | id=T15 | coolant=MQL | stability=High'),
  ('R390-11T308M-PL','Sandvik','Milling','R390-11T308M-PL / R / Shoulder','1130',array['N'],array['MQL','Dry'],array['Shoulder','Aluminium shoulder milling'],array[]::text[],11,'Legacy directory migration','2024-08-01','Source: Manufacturer data | grade=1130 | iso=N | op=Shoulder | confidence=91 | id=T16 | coolant=MQL/Dry | stability=High'),
  ('HM390 TDKT 1505','Iscar','Milling','HM390 TDKT 1505 / T / Face','IC830',array['N'],array['Dry'],array['Face','Face milling non-ferrous'],array[]::text[],6,'Legacy directory migration','2024-05-01','Source: Manufacturer + reviewed | grade=IC830 | iso=N | op=Face | confidence=84 | id=T17 | coolant=Dry | stability=High'),
  ('XOEX 120404R-W07','Walter','Milling','XOEX 120404R-W07 / X / Shoulder','WPP35S',array['P'],array['Wet'],array['Shoulder','Steel shoulder milling'],array[]::text[],18,'Legacy directory migration','2024-07-01','Source: Manufacturer data | grade=WPP35S | iso=P | op=Shoulder | confidence=88 | id=T18 | coolant=Wet | stability=High'),
  ('EDPT 100308-PDER','Kennametal','Milling','EDPT 100308-PDER / E / Face','KCPM40',array['P'],array['Wet'],array['Face','Face milling carbon steel'],array[]::text[],18,'Legacy directory migration','2024-04-01','Source: Manufacturer + reviewed | grade=KCPM40 | iso=P | op=Face | confidence=86 | id=T19 | coolant=Wet | stability=High'),
  ('R245-12T3M-PM','Sandvik','Milling','R245-12T3M-PM / R / Face','4240',array['P'],array['Wet','Dry'],array['Face','High-feed face milling steel'],array[]::text[],18,'Legacy directory migration','2024-09-01','Source: Manufacturer data | grade=4240 | iso=P | op=Face | confidence=94 | id=T20 | coolant=Wet/Dry | stability=High'),
  ('XPMT 060204-DJ','Tungaloy','Milling','XPMT 060204-DJ / X / Shoulder','AH725',array['M'],array['Wet'],array['Shoulder','Stainless shoulder mill'],array[]::text[],6,'Legacy directory migration','2024-06-01','Source: Manufacturer + reviewed | grade=AH725 | iso=M | op=Shoulder | confidence=87 | id=T21 | coolant=Wet | stability=High'),
  ('AXMT 123508-PEER','Mitsubishi','Milling','AXMT 123508-PEER / A / High-feed','MP9130',array['M'],array['Wet'],array['High-feed','Stainless high-feed milling'],array[]::text[],11,'Legacy directory migration','2024-05-01','Source: Manufacturer data | grade=MP9130 | iso=M | op=High-feed | confidence=83 | id=T22 | coolant=Wet | stability=Medium'),
  ('WNMG 080408','Walter','Turning','WNMG 080408 / W / Mixed','WSM30S',array['S'],array['High-P'],array['Mixed','Inconel / superalloys'],array[]::text[],28,'Legacy directory migration','2024-03-01','Source: Manufacturer + reviewed | grade=WSM30S | iso=S | op=Mixed | confidence=82 | id=T23 | coolant=High-P | stability=Medium'),
  ('CNMG 120408-SMR','Sandvik','Turning','CNMG 120408-SMR / C / Roughing','S205',array['S'],array['High-P'],array['Roughing','Titanium roughing'],array['CCGT 09T308-AL'],28,'Legacy directory migration','2024-08-01','Source: Manufacturer data | grade=S205 | iso=S | op=Roughing | confidence=88 | id=T24 | coolant=High-P | stability=High'),
  ('CCGT 09T308-AL','Kennametal','Turning','CCGT 09T308-AL / C / Finishing','KCU10',array['S'],array['High-P'],array['Finishing','Ti-6Al-4V finishing'],array['CNMG 120408-SMR'],28,'Legacy directory migration','2024-07-01','Source: Manufacturer + reviewed | grade=KCU10 | iso=S | op=Finishing | confidence=85 | id=T25 | coolant=High-P | stability=High'),
  ('DCMT 11T304','Tungaloy','Turning','DCMT 11T304 / D / Finishing','T9215',array['H'],array['Dry'],array['Finishing','Hardened steel finishing'],array[]::text[],11,'Legacy directory migration','2024-02-01','Source: Generated estimate | grade=T9215 | iso=H | op=Finishing | confidence=79 | id=T26 | coolant=Dry | stability=High'),
  ('CCGW 09T308-CBN','Sandvik','Turning','CCGW 09T308-CBN / C / Finishing','CB7015',array['H'],array['Dry'],array['Finishing','Hardened steel CBN finishing'],array[]::text[],28,'Legacy directory migration','2024-08-01','Source: Manufacturer data | grade=CB7015 | iso=H | op=Finishing | confidence=91 | id=T27 | coolant=Dry | stability=High'),
  ('16ER 1.5 ISO','Vargus','Threading','16ER 1.5 ISO / External','VKX',array['P'],array['Wet'],array['External','ISO metric external threading'],array['266RG-16MM01F100E','GIPI 3.00E-0.40'],6,'Legacy directory migration','2024-05-01','Source: Manufacturer + reviewed | grade=VKX | iso=P | op=External | confidence=87 | id=T28 | coolant=Wet | stability=High'),
  ('266RG-16MM01F100E','Sandvik','Threading','266RG-16MM01F100E / External','1135',array['P'],array['Wet'],array['External','Multi-pitch threading'],array['16ER 1.5 ISO','GIPI 3.00E-0.40'],18,'Legacy directory migration','2024-09-01','Source: Manufacturer data | grade=1135 | iso=P | op=External | confidence=90 | id=T29 | coolant=Wet | stability=High'),
  ('16IR AG60','Iscar','Threading','16IR AG60 / Internal','IC228',array['M'],array['Wet'],array['Internal','Internal stainless threading'],array['N123H2-0400-0004-GM'],11,'Legacy directory migration','2024-04-01','Source: Manufacturer + reviewed | grade=IC228 | iso=M | op=Internal | confidence=84 | id=T30 | coolant=Wet | stability=Medium'),
  ('HPR 12.00 H7','Mapal','Reaming','HPR 12.00 H7 / Finishing','Carbide',array['P'],array['Wet'],array['Finishing','H7 tolerance steel reaming'],array[]::text[],18,'Legacy directory migration','2024-06-01','Source: Manufacturer + reviewed | grade=Carbide | iso=P | op=Finishing | confidence=86 | id=T31 | coolant=Wet | stability=High'),
  ('EX-SUS-RM 10.00','OSG','Reaming','EX-SUS-RM 10.00 / Finishing','PM',array['M'],array['Wet'],array['Finishing','Stainless precision reaming'],array[]::text[],6,'Legacy directory migration','2024-02-01','Source: Generated estimate | grade=PM | iso=M | op=Finishing | confidence=81 | id=T32 | coolant=Wet | stability=High'),
  ('TNMG 220408-PR','Sandvik','Turning','TNMG 220408-PR / T / Roughing','GC4315',array['P'],array['Wet'],array['Roughing','Heavy P-group roughing'],array['TNMG 160408-NF'],18,'Legacy directory migration','2024-08-01','Source: Manufacturer data | grade=GC4315 | iso=P | op=Roughing | confidence=92 | id=T33 | coolant=Wet | stability=High'),
  ('TNMG 160408-NF','Iscar','Turning','TNMG 160408-NF / T / Finishing','IC8250',array['P'],array['Wet','Dry'],array['Finishing','P-group fine finishing'],array['TNMG 220408-PR'],11,'Legacy directory migration','2024-07-01','Source: Manufacturer + reviewed | grade=IC8250 | iso=P | op=Finishing | confidence=89 | id=T34 | coolant=Wet/Dry | stability=High'),
  ('GIPI 3.00E-0.40','Iscar','Threading','GIPI 3.00E-0.40 / Grooving','IC908',array['P'],array['Wet'],array['Grooving','Internal grooving steel'],array['16ER 1.5 ISO','266RG-16MM01F100E'],11,'Legacy directory migration','2024-05-01','Source: Manufacturer + reviewed | grade=IC908 | iso=P | op=Grooving | confidence=83 | id=T35 | coolant=Wet | stability=Medium'),
  ('N123H2-0400-0004-GM','Sandvik','Threading','N123H2-0400-0004-GM / Grooving','1125',array['M'],array['Wet'],array['Grooving','External grooving stainless'],array['16IR AG60'],18,'Legacy directory migration','2024-08-01','Source: Manufacturer data | grade=1125 | iso=M | op=Grooving | confidence=87 | id=T36 | coolant=Wet | stability=High')
on conflict (sku) do update
set
  brand = excluded.brand,
  family = excluded.family,
  type_geometry = excluded.type_geometry,
  coating = excluded.coating,
  material_compat = excluded.material_compat,
  machine_type = excluded.machine_type,
  application = excluded.application,
  alternatives_to = excluded.alternatives_to,
  price_hint_eur = excluded.price_hint_eur,
  source_url = excluded.source_url,
  last_updated = excluded.last_updated,
  notes = excluded.notes;